# Generated by Django 4.2.4 on 2023-10-01 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_remove_task_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
    ]
