# Generated by Django 4.2.4 on 2023-10-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0007_alter_task_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(null=True),
        ),
    ]
